export default {
  "01-folder-setup": "1. Folder setup",
  "02-create-file": "2. Create the file",
  "03-environment": "3. Environment",
  "04-file-shape": "4. File shape",
  "05-rotation-info": "5. Rotation information",
  "06-toggles": "6. Toggles",
  "07-options": "7. Options",
  "08-spellbook": "8. Global spellbook",
  "09-unit-lookups": "9. Live unit lookups",
  "10-pulse-contract": "10. Pulse contract",
  "11-out-of-combat-pulse": "11. Out-of-combat pulse",
  "12-engagement-pulse": "12. Engagement pulse",
  "13-combat-pulse": "13. Combat pulse",
  "14-spell-policy": "14. Spell policy",
  "15-spell-targets": "15. Spell targets",
  "16-combat-priority": "16. Combat priority",
  "17-pet-maintenance": "17. Pet maintenance",
  "18-pet-assist": "18. Pet combat assist",
  "19-pet-specific-policy": "19. Class-specific pet policy",
  "20-healthstone-availability": "20. Healthstone availability",
  "21-healthstone-use": "21. Healthstone use",
  "22-wand-maintenance": "22. Wand maintenance",
  "23-multipull-target-cap": "23. Multipull target cap",
  "24-multipull-pet-handoff": "24. Multipull pet handoff",
  "25-multipull-pulse": "25. Multipull pulse",
  "26-complete-source": "26. Complete source",
  "27-audit-and-validation": "27. Audit and validation",
  "28-movement-ownership": "28. Movement ownership",
  "29-movement-path-request": "29. Request a path",
  "30-movement-path-following": "30. Follow a path",
  "31-movement-cleanup": "31. Movement cleanup",
  "32-movement-fallback": "32. Bounded movement fallback",
};
